# Default values for http-helm-workshop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: example.com/helm-workshop/api-demo
  pullPolicy: Always

nameOverride: "helm-workshop"
fullnameOverride: "helm-workshop"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-0-24
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: sample.helm-workshop.example.com
      paths:
        - /hello

  tls:
    - hosts:
        - sample.helm-workshop.example.com
      secretName: tls-helm-workshop
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

